### ISSUE TITLE
Some class paths are created with double backslashes if source file contains some namespace classes

### ISSUE THREAD

**Issue by localhorst** [sabbelasichon/typo3-ns-converter#2]
This seems to be a bug.

For example:
1.
` * @param \DateTime $startDate`

converts to 

`* @param \\DateTime $startDate`

2.
` catch (\TYPO3\CMS\Extbase\Mvc\Exception\InvalidArgumentValue $exception) `

converts to 

`catch (\TYPO3\CMS\Extbase\Mvc\\Exception\InvalidArgumentValue $exception)`

**Comment by sabbelasichon** [comment]
Please update, this is fixed in the latest commits already. Had this bug by myself.
